1. 整理好配置文件名字读取与工单关联的功能

diff --git a/package_update/package-utils b/package_update/package-utils
--- a/package_update/package-utils
+++ b/package_update/package-utils
@@ -11,10 +11,9 @@ ECHO="echo "
 EGREP="egrep"
 CMD_LIME="$0 $*"
 MODE="UNKNOW-MODE"
-PACKAGE_NAME=""
 CONFILE_NAME=""
 
-EXCUTE_FLAG="NO"
+OVERRIDE_FLAG="NO"
 
 
 AWK_FORMAT_ABS_PAHT="/home/mcb3user/jigc/shell/update_tools/package-update.awk"
@@ -23,7 +22,7 @@ help(){
 cat  << EOF
 ########################################################################
 # Author      : jigc 
-# Script Name : svn-mark
+# Script Name : $0
 # Description : 对svn改动文件进行标记
 # Version     : V2.0
 # Usage       : $0 -r <起始版本号>:<结束版本号|HEAD> -f <配置文件绝对路径> [-d parrten] [dirlist ... ]
@@ -43,14 +42,11 @@ EOF
 
 }
 
-# package-update.sh --create-mode --conf /home/mcb3user/jigc/shell/update_tools/update.conf  --package-name  ~/jigc/update.tgz
-# ./package-update.sh --extract-mode --conf ~/shell/update_tools/update.conf  --package-name  ~/update.tgz  --backup-package-name  ~/shell/update_tools/back-xxx.tgz
+# package-utils --create-mode --conf /home/mcb3user/jigc/shell/update_tools/conf/KR-20150112-11224364.conf 
+# ./package-utils --extract-mode --conf ~/shell/update_tools/update.conf  --package-name  ~/update.tgz  --backup-package-name  ~/shell/update_tools/back-xxx.tgz
 
-# ./package-update.sh --extract-mode  --excute-update --conf ~/shell/update_tools/update.conf  --package-name  ~/update.tgz  --backup-package-name  ~/shell/update_tools/back-xxx.tgz
+# ./package-utils --extract-mode  --excute-override --conf ~/shell/update_tools/update.conf 
 
-
-# 打包的临时目标路径在打包完成后将删除
-TAR_PACKAGE_TMP_DIR="/tmp/package-utile-output.$$"
 
 
 #获取参数##########################
@@ -65,18 +61,16 @@ do
 		help 
 		exit 0
 		;;
-	--package-name)
-		PACKAGE_NAME=$2
-		shift 
-		;;
-	--backup-package-name)
-		BACKUP_PACKAGE_NAME=$2
-		shift 
-		;;		
+		
 	--conf)
 		
 		CONFILE_NAME=$2 
 		
+		#获取工单号
+		
+		f=`basename ${CONFILE_NAME}`
+		export ORDER_NAME=`echo $f | sed 's|\.conf||'`
+
 		. $CONFILE_NAME
 		shift 
 		;;
@@ -90,8 +84,8 @@ do
 	--extract-mode)
 		MODE="EXTRACT-MODE"
 		 ;;
-	--excute-update)
-		EXCUTE_FLAG="YES"
+	--excute-override)
+		OVERRIDE_FLAG="YES"
 		;;
     --)
 		
@@ -104,33 +98,45 @@ done
 ###################################
 
 
+# 打包的临时目标路径在打包完成后将删除
+UTILS_WORKING_DIR="$HOME/package-utils-output/${ORDER_NAME}"
+
+# 压缩文件临时文件夹 
+TAR_PACKAGE_TMP_DIR="${UTILS_WORKING_DIR}/tmp/"
+
+
+# 
+UPDATE_PACKAGE_NAME="${UTILS_WORKING_DIR}/${ORDER_NAME}-UPDATE.tgz"
+BACKUP_PACKAGE_NAME="${UTILS_WORKING_DIR}/${ORDER_NAME}-BACKUP.tgz"
 
 
 #main 入口#################################
 
+clean_up(){
+	$ECHO "rm -rf ${TAR_PACKAGE_TMP_DIR}"
+}
+
 create_init(){
 
-
+$ECHO 
+$ECHO 
 $ECHO "################################################################################"
-$ECHO "# SVN 版本号           	  : ${SVN_VERSION}" 
+$ECHO "# SVN 版本号               : ${SVN_VERSION}" 
 $ECHO "# SVN 基础路径             : ${SVN_BASE_FIEL_DIR}"
-$ECHO "# 更新压缩包绝对值路径     : ${PACKAGE_NAME}" 
+$ECHO "# 更新压缩包绝对值路径     : ${UPDATE_PACKAGE_NAME}" 
 $ECHO "# 配置文件绝对值路径       : ${CONFILE_NAME}"
 $ECHO "# 生产的目标路径           : ${DEST_DIR}"
 $ECHO "# 压缩文件临时文件夹       : ${TAR_PACKAGE_TMP_DIR}"
 $ECHO "# 命令行                   : ${CMD_LIME}"
 $ECHO "################################################################################"
-
-
-	[ ! -d ${DEST_DIR} ] && mkdir -p ${DEST_DIR}
-	cd $SVN_BASE_FIEL_DIR 
 	
+	clean_up
+	mkdir -p ${UTILS_WORKING_DIR}
+	mkdir -p ${TAR_PACKAGE_TMP_DIR}
 
 }
 
-clean_up(){
-	$ECHO "rm ${DEST_DIR}"
-}
+
 
 
 my_copy(){
@@ -149,21 +155,30 @@ my_copy(){
 }
 
 
-
-
-# 打包更新的文件
-
-
-
 create_process(){
 	create_init		# 初始化函数
+	
 	
 	# 执行钩子函数
 	$ECHO "\n\n[HOOK PRE-PACKAGE] BEGINE...\n" 
 	(pre_package)
 	$ECHO "\n[HOOK PRE-PACKAGE] END...\n\n" 
 	
-	# 拷贝更新文件到指定文件夹
+	$ECHO "\n[MESSAGE]	改变路径到SVN目录下: ${SVN_BASE_FIEL_DIR}\n"
+	cd $SVN_BASE_FIEL_DIR 
+	
+	# 更新 SVN 到指定版本号
+	svn up -r ${SVN_VERSION}
+	if [ $? -eq 0 ]; then
+		$ECHO  "[MESSAGE]	SVN UPDATE TO VERSION ${SVN_VERSION} SUCCESS..."
+	else
+		$ECHO  "[ERROR]		SVN UPDATE TO VERSION ${SVN_VERSION} FAILT..."
+		exit 1
+	fi
+	
+	# 解析配置文件并拷贝更新文件到指定文件夹
+	
+	$ECHO "\n[MESSAGE]	解析配置文件并检查cksum至后拷贝更新文件到指定文件夹: ${TAR_PACKAGE_TMP_DIR}\n"
 	file_list | awk  -f ${AWK_FORMAT_ABS_PAHT} TAR_PACKAGE_TMP_DIR=${TAR_PACKAGE_TMP_DIR} DEST_DIR=${DEST_DIR} | while read line ; do
 		
 		$ECHO  $line | $EGREP -q "^CP"
@@ -178,29 +193,23 @@ create_process(){
 		if [ $? -eq 0 ]; then
 			$ECHO "[MESSAGE] $line"
 		fi
-
-		
 	done  
+	
 	
 	
 	# 切换工作目录到生成文件的根目录
 	
-	[ ! -d ${TAR_PACKAGE_TMP_DIR} ] && mkdir -p ${TAR_PACKAGE_TMP_DIR}
-	$ECHO "[MESSAGE]	改变路径到压缩文件临时文件夹下: ${TAR_PACKAGE_TMP_DIR}\n\n"
-	cd ${TAR_PACKAGE_TMP_DIR} 
+	$ECHO "\n[MESSAGE]	改变路径到压缩文件临时文件夹下: ${TAR_PACKAGE_TMP_DIR} ..."
+	cd "${TAR_PACKAGE_TMP_DIR}"
 	
-	
-	$ECHO  "[MESSAGE]	开始打包所有需要更新的文件:[ ${PACKAGE_NAME} ] ...\n"
-	# 打包的时候需要过滤文件夹
-	sync
-	# find . -type f | xargs tar -cvf package.tgz 
-	tar -cvf ${PACKAGE_NAME} *
+	$ECHO  "[MESSAGE]	开始打包所有需要更新的文件到:[ ${UPDATE_PACKAGE_NAME} ] ...\n"
+	tar -cvf "${UPDATE_PACKAGE_NAME}" *
 	
 	if [ $? -eq 0 ]; then
-		_file_cnt=`tar -tf ${PACKAGE_NAME} | sed -e '/\/$/d' | wc -l`
-		$ECHO  "\n[MESSAGE]	PACKAGE FILE:[ ${PACKAGE_NAME}(total:$_file_cnt) ] SUCCESS..."
+		_file_cnt=`tar -tf "${UPDATE_PACKAGE_NAME}" | sed -e '/\/$/d' | wc -l`
+		$ECHO  "\n[MESSAGE]	PACKAGE FILE:[ ${UPDATE_PACKAGE_NAME}(total:$_file_cnt) ] SUCCESS..."
 	else
-		$ECHO  "\n[ERROR]	PACKAGE FILE:[ ${PACKAGE_NAME} ] FAILT..."
+		$ECHO  "\n[ERROR]	PACKAGE FILE:[ ${UPDATE_PACKAGE_NAME} ] FAILT..."
 		exit 1
 	fi
 	
@@ -216,7 +225,8 @@ create_process(){
 
 extract_init(){
 
-	cd /
+$ECHO 
+$ECHO 
 $ECHO "################################################################################"
 $ECHO "# 新压缩包绝对值路径       : ${PACKAGE_NAME}" 
 $ECHO "# 备份压缩包绝对路径       : ${BACKUP_PACKAGE_NAME}" 
@@ -227,11 +237,18 @@ $ECHO "# 执行备份                 : ${EXCUTE_FLAG}"
 $ECHO "# 命令行                   : ${CMD_LIME}"
 $ECHO "################################################################################"
 
+	clean_up
+	mkdir -p ${TAR_PACKAGE_TMP_DIR}
+	if [ ! -f ${UPDATE_PACKAGE_NAME} ]; then 
+		$ECHO  "[ERROR]	系统找不到指定单号的更新包:[ ${UPDATE_PACKAGE_NAME} ] ..."
+		exit 1
+	fi	
 
 }
 
 
 extract_process(){
+
 	extract_init
 	
 	# 执行钩子函数
@@ -245,19 +262,14 @@ extract_process(){
 	_add_cnt=0
 	
 	
-	tar -tf $PACKAGE_NAME | sed -e '/\/$/d' | while read file; do
+	tar -tf ${UPDATE_PACKAGE_NAME} | sed -e '/\/$/d' | while read file; do
 		if [ -f $file ]; then
 			let "_update_cnt += 1"
 			$ECHO  "[MESSAGE]	FILE:[ /${file} ] WILL BE UPDATE ..."
-			
-			
-			if [ "${EXCUTE_FLAG}" = "YES" ]; then
-				my_copy "/$file"  "${TAR_PACKAGE_TMP_DIR}/$file"
-			fi
+			my_copy "/$file"  "${TAR_PACKAGE_TMP_DIR}/$file"
 		else
 			let "_add_cnt += 1"
 			$ECHO  "[WARNMING]	FILE:[ /${file} ] WILL BE ADD..."
-			exit 1
 		fi
 	done
 	let "_total = _update_cnt + _add_cnt"
@@ -266,15 +278,16 @@ extract_process(){
 	$ECHO  "\n[WARMING]	***  Total(${_total}), Update(${_update_cnt}),  Add(${_add_cnt}) ***\n"
 	
 	
+
+
+	if [ ${_update_cnt} -gt 0 ]; then
 	
-	if [ "${EXCUTE_FLAG}" = "YES" ]; then
 		# 备份原文件 
-		$ECHO "[MESSAGE]	改变路径到压缩文件临时文件夹下: ${TAR_PACKAGE_TMP_DIR}\n\n"
+		$ECHO "[MESSAGE]	改变路径到压缩文件临时文件夹下: ${TAR_PACKAGE_TMP_DIR}\n"
 		cd ${TAR_PACKAGE_TMP_DIR} 
 		
-		$ECHO  "[MESSAGE]	开始备份所有需要更新的文件:[ ${BACKUP_PACKAGE_NAME} ] ...\n"
-		sync
-		# find . -type f | xargs tar -cvf package.tgz 
+		$ECHO  "[MESSAGE]	开始备份所有需要更新的文件到:[ ${BACKUP_PACKAGE_NAME} ] ...\n"
+	
 		tar -cvf ${BACKUP_PACKAGE_NAME} *
 		
 		if [ $? -eq 0 ]; then
@@ -284,15 +297,15 @@ extract_process(){
 			$ECHO  "\n[ERROR]	PACKAGE FILE:[ ${BACKUP_PACKAGE_NAME} ] FAILT..."
 			exit 1
 		fi
-	else
+	else		#  ${_update_cnt} = 0 为本次更新都是新增文件并未修改文件，所以无需备份
+		$ECHO "[MESSAGE]	本次更新都是新增文件并未修改文件，所以无需备份 ...\n"
+	fi 
+	
+	
+	if [ "${OVERRIDE_FLAG}" = "YES" ]; then
 		# 备份原文件 
-		$ECHO "[MESSAGE]	改变路径到压缩文件临时文件夹下: ${TAR_PACKAGE_TMP_DIR}\n\n"
-		
-		$ECHO  "[MESSAGE]	开始备份所有需要更新的文件:[ ${BACKUP_PACKAGE_NAME} ] ...\n"
-		
+		$ECHO "[MESSAGE]	更新文件: ${TAR_PACKAGE_TMP_DIR}\n\n"
 	fi
-	
-	
 	
 	
 	# 执行钩子函数
